### ISSUE TITLE
Does not work very well with Translatable module

### ISSUE THREAD

**Issue by mrguits** [titledk/silverstripe-calendar#32] opened 2016-02-10 11:55 UTC
When clicking buttons in CMS (for instance Past Events)  The action part of the links appends the querystring  

i.e.

/admin/calendar/?Locale=sv_SEpastevents/

**Comment by anselmdk** [comment] 2016-02-10 14:23
I think this is a duplicate of #4 - there's also a solution to it there. Pull requests very welcome if that works for you.

**Closed by anselmdk** 2016-02-10 14:23 UTC
