### ISSUE TITLE
Creating Calendar Fails on v3.1.15 - Blank Screen

### ISSUE THREAD

**Issue by luminousmg** [titledk/silverstripe-calendar#7] opened 2015-10-05 22:57 UTC
Hello,

I am having trouble getting this calendar module to work in the latest stable release of Silverstripe (v3.1.15).  I tried installing dev-master and 1.0.0 with composer.  The module installs correctly, but when I try to add a new calendar, I get a blank "grey" screen after clicking save.  After adding an event, the module becomes unresponsive and I also get a grey screen.  The CMS navigation is still rendered.

The site is in dev mode and there are no errors in the apache log file.

Any tips?

Thanks!

**Comment by anselmdk** [comment] 2015-10-21 09:17
@luminousmg I finally set the demo back up again, and updated to the latest version in the `3.1` line so far: https://github.com/titledk/silverstripe-calendar-demo/commit/855912c7bc5997b536d00585846d9daf8e6794ea

I can't reproduce your problem.

Have a look at http://calendar.demo.title.dk, it seems to work there.

I'm closing this for now. Feel free to reopen if the issue persists for you. I'd suggest downloading the demo and trying it there though.

**Closed by anselmdk** 2015-10-21 09:17 UTC
